#!/usr/bin/env bash

if [[ -z "$RUNNING_IN_DOCKER" ]]; then
    docker run --rm -it \
        -e RUNNING_IN_DOCKER=true \
        -v $(pwd):/root/workspace \
        -v /tmp/poetry-cache:/root/.cache \
        -w /root/workspace \
        $(docker build -q -f docs.dockerfile .) \
        ./make-diagrams
else
    source ~/.bashrc
    poetry install

    for diagram in src/*; do
        if [[ "$diagram" != __init__* ]]; then
            poetry run python $diagram
        fi
    done
fi